### ISSUE TITLE
“Read More” button missing in "latest news" and blog archive

### ISSUE THREAD

**Issue by pale-bluedot** [anphira/kaya#11]
Hi,

I published an article recently and I noticed the button to "read more" that's usually below the excerpt is missing in both the "latest news" on my home page and in the archive page. It's been some months since I last published a post so maybe something changed.
Thanks in advance.

![yiFioPH](https://github.com/anphira/kaya/assets/72536144/b10531e9-6767-4129-81bf-879c7f235fe8)

**Comment by anphira** [comment]
If it is only missing on one of the blog posts it is most likely related to your content. Theme issues would normally affect all of the items, not one specifically.

**Comment by pale-bluedot** [comment]
I figured it out. I removed the text I inserted into the "excerpt" box and let WordPress handle the summary it shows on the blog/home page. The "Read More" button then becomes visible.

**Comment by anphira** [comment]
In version 2.0 of the theme, this functionality will be improved for authors. The default WP handling is to display "read more" only on auto excerpts. In version 2.0 the theme customizer > Blog area checkbox for the read more will control both automatic excerpts & manual ones. Planned release sometime in Sept 2024.
